#[browser]
#showSidebarNavigation = false  # Oculta el menú lateral (opcional), esto se hace por un 
[server]
enableXsrfProtection = false
enableCORS = false
#gatherUsageStats = false

[theme]
base = "dark"
#base = "light"

